

--  Generar SQL 
--  Versión:                   	V7R2M0 140418 
--  Generado en:              	05/08/20 11:39:39 
--  Base de datos relacional:       	TSILDES1 
--  Opción de estándares:          	DB2 for i 
CREATE OR REPLACE PROCEDURE CAHUSRLIB.PPAGOSD01 ( 
    IN ENTRADA CHAR(4),
	OUT RESP CHAR(10) ) 
	LANGUAGE RPGLE 
	SPECIFIC CAHUSRLIB.PPAGOSD01 
	NOT DETERMINISTIC 
	NO SQL 
	CALLED ON NULL INPUT 
	EXTERNAL NAME 'CAHUSRLIB/PPAGOSD01' 
	PARAMETER STYLE GENERAL WITH NULLS ; 
  
GRANT ALTER , EXECUTE   
ON SPECIFIC PROCEDURE CAHUSRLIB.PPAGOSD01
TO ALDONCMS WITH GRANT OPTION ; 
  
GRANT ALTER , EXECUTE   
ON SPECIFIC PROCEDURE CAHUSRLIB.PPAGOSD01 
TO CAHORRO WITH GRANT OPTION ; 
  
GRANT EXECUTE   
ON SPECIFIC PROCEDURE CAHUSRLIB.PPAGOSD01 
TO PUBLIC ; 




  

