--  Generar SQL 
--  Versión:                   	V7R2M0 140418 
--  Generado en:              	05/08/20 11:39:39 
--  Base de datos relacional:       	TSILDES1 
--  Opción de estándares:          	DB2 for i 
CREATE OR REPLACE PROCEDURE CAHUSRLIB.SP_CANCELADOS (
    IN DESDE CHAR(8)
    ,IN HASTA CHAR(8)
    ,IN FILTRO CHAR(1)
    ,IN FREC CHAR(1) 
	,OUT RESP INTEGER ) 
	LANGUAGE RPGLE 
	SPECIFIC CAHUSRLIB.SP_CANCELADOS 
	NOT DETERMINISTIC 
	NO SQL 
	CALLED ON NULL INPUT 
	EXTERNAL NAME 'CAHUSRLIB/RPG1055' 
	PARAMETER STYLE GENERAL WITH NULLS ; 
  
GRANT ALTER , EXECUTE   
ON SPECIFIC PROCEDURE CAHUSRLIB.SP_CANCELADOS 
TO ALDONCMS WITH GRANT OPTION ; 
  
GRANT ALTER , EXECUTE   
ON SPECIFIC PROCEDURE CAHUSRLIB.SP_CANCELADOS 
TO CAHORRO WITH GRANT OPTION ; 
  
GRANT EXECUTE   
ON SPECIFIC PROCEDURE CAHUSRLIB.SP_CANCELADOS 
TO PUBLIC ; 

