--  Generar SQL 
--  Versión:                   	V7R2M0 140418 
--  Generado en:              	05/08/20 11:39:39 
--  Base de datos relacional:       	TSILDES1 
--  Opción de estándares:          	DB2 for i 
CREATE OR REPLACE PROCEDURE CAHUSRLIB.SP_PPAGOSP ( 
	OUT RESP INTEGER ) 
	LANGUAGE RPGLE 
	SPECIFIC CAHUSRLIB.SP_PPAGOSP 
	NOT DETERMINISTIC 
	NO SQL 
	CALLED ON NULL INPUT 
	EXTERNAL NAME 'CAHUSRLIB/PPAGOS001' 
	PARAMETER STYLE GENERAL WITH NULLS ; 
  
GRANT ALTER , EXECUTE   
ON SPECIFIC PROCEDURE CAHUSRLIB.SP_PPAGOSP 
TO ALDONCMS WITH GRANT OPTION ; 
  
GRANT ALTER , EXECUTE   
ON SPECIFIC PROCEDURE CAHUSRLIB.SP_PPAGOSP 
TO CAHORRO WITH GRANT OPTION ; 
  
GRANT EXECUTE   
ON SPECIFIC PROCEDURE CAHUSRLIB.SP_PPAGOSP 
TO PUBLIC ; 
  
